---
- name: demo
  hosts: localhost
  sources:
    - name: kafka
      ansible.eda.kafka:
        topic: demo-events
        host: 10.0.0.3
        port: 9092
  rules:
    - name: debug events
      condition: true
      action:
        debug:
